server:
  port: 8080

spring:
  datasource:
    # Use a file-based H2 DB so data persists across restarts
    # DB files will be created under backend/db/transformerdb.*
    url: "jdbc:h2:file:./db/transformerdb;MODE=PostgreSQL"
    driver-class-name: org.h2.Driver
    username: sa
    password: ""
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

  h2:
    console:
      enabled: true
      path: /h2-console

app:
  jwt:
    secret: change-me-in-prod-32-bytes-minimum-secret
    expiry-seconds: 86400

  ai:
    # Path to Python interpreter (e.g., python, python3, or full path)
    python: python
    # Relative to backend working dir; default points to repo AI/analyze.py
    script: ../AI/analyze.py

# Allow simple local integration
cors:
  allowed-origins: "http://localhost:3000"
