server:
  port: ${PORT:8080}

spring:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

app:
  jwt:
    secret: ${APP_JWT_SECRET:defaultSecretKey}
    expiry-seconds: 86400
  ai:
    python: py
    script: ./AI/analyze.py

cors:
  allowed-origins: "http://localhost:3000, https://apex-grid-transformer-tracker.vercel.app"
