name: Backend Docker build

on:
  workflow_run:
    workflows: ["Merge main into target"]
    types:
      - completed

permissions:
  contents: read

jobs:
  detect-and-build:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Determine target branch
        run: |
          # workflow_run payload contains the head_branch (the branch that triggered the original run)
          echo "TRIGGER_BRANCH=${{ github.event.workflow_run.head_branch }}" >> $GITHUB_ENV

      - name: Detect backend changes between target and main
        id: detect
        run: |
          set -euo pipefail
          TARGET=${TRIGGER_BRANCH:-local}
          echo "Checking changes in backend/ between origin/$TARGET and origin/main"
          git fetch origin main
          git fetch origin $TARGET || true
          if git ls-remote --exit-code --heads origin "$TARGET" >/dev/null 2>&1; then
            CHANGED=$(git diff --name-only origin/$TARGET..origin/main || true)
          else
            echo "origin/$TARGET not found — treating as changed"
            CHANGED="backend/"
          fi
          echo "Changed files:\n$CHANGED"
          if printf "%s" "$CHANGED" | grep -E '^backend/' >/dev/null 2>&1; then
            echo "backend_changed=true" >> $GITHUB_OUTPUT
          else
            echo "backend_changed=false" >> $GITHUB_OUTPUT
          fi

      - name: Build and push Docker image
        if: steps.detect.outputs.backend_changed == 'true'
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
        run: |
          set -euo pipefail
          echo "Backend changed — building image"
          echo "$DOCKERHUB_TOKEN" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
          docker build -t "$DOCKERHUB_USERNAME/transformer-tracker-local:latest" backend
          docker push "$DOCKERHUB_USERNAME/transformer-tracker-local:latest"
